# Generated by Django 3.0.4 on 2020-03-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=128)),
                ('previous_value', models.CharField(max_length=128)),
                ('new_value', models.CharField(max_length=128)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Clients')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='manager_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Manager'),
        ),
        migrations.AddField(
            model_name='clients',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Employee'),
        ),
    ]
