# Generated by Django 3.0.4 on 2020-03-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20200304_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
            preserve_default=False,
        ),
    ]
